### ISSUE TITLE
Update Torlock

### ISSUE THREAD

**Issue by ngosang** [DoumanAsh/qBittorrent-Search-Plugins#2]
@DoumanAsh Update Torlock, the Name is displayed wrong. Also update the icon and the wiki:
https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins

Thanks.

**Comment by DoumanAsh** [comment]
Can you please share example?

**Comment by ngosang** [comment]
Python 3. See the Name column vs https://www.torlock.com/all/torrents/batman.html
![](http://i.imgur.com/GSsPQwz.png)

**Comment by DoumanAsh** [comment]
Ok got it. Will fix that.

**Comment by DoumanAsh** [comment]
Done.
I would prefer to re-write it, but i was too lazy so i just fixed name displaying :)

**Comment by ngosang** [comment]
Update the icon if you have time.

**Comment by Pireo** [comment]
Now it detects the names fine, but try to search, for exemple, "russian", "spanish", etc... the first results, in order by seeders, will have a "full version", "high definition", and "latest top release" which will redirect to a dangerous site. Thanks for your dedication anyway, guys.

**Comment by DoumanAsh** [comment]
@Pireo 
Well it is torlock bad results...
I'll think about filtering it later. But anyway Torlock is just bad.

**Comment by DoumanAsh** [comment]
@Pireo 
Filtering of malicious is added in scope of https://github.com/DoumanAsh/qBittorrent-Search-Plugins/commit/5c29834f7f268acff53de7222f1bcbd200e21c0c

**Comment by Pireo** [comment]
The only strange thing, if I search "movie" it doesn't find anything, just to inform you, but the plugin is definitely ok now, Thanks.
