### ISSUE TITLE
Update Tokyo Toshokan: description links don't work

### ISSUE THREAD

**Issue by ngosang** [DoumanAsh/qBittorrent-Search-Plugins#3]
@DoumanAsh Update Tokyo Toshokan, the description links don't work. You can link to details page: https://tokyotosho.info/details.php?id=917975

Remember to update: https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins

Thanks.

**Comment by DoumanAsh** [comment]
Done.
Thanks for reporting
